if not marked_backward: move_backward()
if not random_choice(): clear_flag_a()
if not can_move_forward: nop()
if not can_move_forward: move_forward()
if marked_backward: set_flag_a()
if marked_forward: turn_right()
if not flag_a: set_flag_a()
unmark_position()
if not marked_current: nop()
if flag_a: set_flag_b()
if not marked_current: nop()
if not marked_backward: turn_right()
if not marked_backward: mark_position()
if not flag_a: move_forward()
if can_move_forward: clear_flag_a()
if not marked_backward: set_flag_b()
if random_choice(): move_forward()
if not getting_closer(): turn_right()
if flag_b: unmark_position()
if not flag_a: move_forward()
if not flag_a: move_forward()
if random_choice(): turn_left()
if getting_closer(): clear_flag_a()
if marked_current: turn_left()
if marked_forward: clear_flag_a()